<?php
/* Theme 01 - Villa Rosa Resort. Rebuilt from clean HTML source 1.0.0. */

$BASE = function_exists( 'sbt_media_base_url' ) ? sbt_media_base_url() : 'assets/uploads/';

$IMG = array(
	'favicon' => $BASE . '2025/02/cropped-favicon-villarosaresort-conversano-270x270.png',
	'logo' => $BASE . '2025/02/logo02-white-villarosaresort-conversano.png',
	'logo_foot' => $BASE . '2025/02/logo03-white-villarosaresort-conversano.png',
	'lgbtq' => $BASE . '2025/07/lgbtq.png',
	'welcome' => $BASE . '2025/03/8dc77600-2d08-4399-8d34-9019c864a9ae.jpg',
	'hero' => $BASE . '2025/03/8dc77600-2d08-4399-8d34-9019c864a9ae.jpg',
	'a1' => $BASE . '2025/03/a1-1240-900.jpg',
	'a5' => $BASE . '2025/03/a5-1240-900.jpg',
	'room' => $BASE . '2025/03/350a927d-d95e-401a-9c30-845b04364bc4.jpg',
	'room2' => $BASE . '2025/03/VMLX0557.jpg',
	'garden' => $BASE . '2025/03/7a97973d-9ff7-4e3e-bb14-7b6909ac32a7.jpg',
	'villa' => $BASE . '2025/03/p-YLCX1349.jpg',
	'lunch' => $BASE . '2025/03/Typical-lunch-or-dinner-in-Villa-Rosa-02.jpg',
	'spa_remote' => $BASE . '2025/03/Immagine-WhatsApp-2024-05-03-ore-19.16.09_9adc16c9.jpg',
	'wellness_corridor' => function_exists( 'sbt_asset_url' ) ? sbt_asset_url( 'assets/images/wellness-corridor.jpg' ) : 'assets/images/wellness-corridor.jpg',
	'apulian_table' => function_exists( 'sbt_asset_url' ) ? sbt_asset_url( 'assets/images/apulian-table.jpg' ) : 'assets/images/apulian-table.jpg',
	'apulian_breakfast' => function_exists( 'sbt_asset_url' ) ? sbt_asset_url( 'assets/images/apulian-breakfast.jpg' ) : 'assets/images/apulian-breakfast.jpg',
	'conversano_town' => function_exists( 'sbt_asset_url' ) ? sbt_asset_url( 'assets/images/conversano-town.jpg' ) : 'assets/images/conversano-town.jpg',
	'room_detail' => function_exists( 'sbt_asset_url' ) ? sbt_asset_url( 'assets/images/room-detail.jpg' ) : 'assets/images/room-detail.jpg',
	'jacuzzi_detail' => function_exists( 'sbt_asset_url' ) ? sbt_asset_url( 'assets/images/jacuzzi.jpg' ) : 'assets/images/jacuzzi.jpg',
	'sauna_detail' => function_exists( 'sbt_asset_url' ) ? sbt_asset_url( 'assets/images/sauna.jpg' ) : 'assets/images/sauna.jpg',
	'turkish_bath_detail' => function_exists( 'sbt_asset_url' ) ? sbt_asset_url( 'assets/images/turkish-bath.jpg' ) : 'assets/images/turkish-bath.jpg',
	'relax_lounge_detail' => function_exists( 'sbt_asset_url' ) ? sbt_asset_url( 'assets/images/relax-lounge.jpg' ) : 'assets/images/relax-lounge.jpg',
	'gym_detail' => function_exists( 'sbt_asset_url' ) ? sbt_asset_url( 'assets/images/gym.jpg' ) : 'assets/images/gym.jpg',
);

$SITE = array(
	'name' => 'Villa Rosa Resort',
	'tagline' => 'An Apulia Villa',
	'vimeo' => '687646681',
	'wa' => 'https://wa.me/393206090558',
	'phone1' => '+39 338 250 7545',
	'phone1_t' => '+393382507545',
	'phone2' => '+39 320 609 0558',
	'phone2_t' => '+393206090558',
	'email' => 'villarosasuites@gmail.com',
	'address' => 'Viale P. Orlando, 1<br/>70014 Conversano (Bari)<br/>Puglia, Italy',
	'map' => 'https://maps.app.goo.gl/PjihQ243sU2ZcT4m9',
	'map_embed' => 'https://www.google.com/maps?q=Villa%20Rosa%20Resort%20Conversano&output=embed',
	'facebook' => 'https://www.facebook.com/villarosaresort/',
	'instagram' => 'https://www.instagram.com/villarosaresortpuglia/',
	'lang_primary' => 'EN',
	'lang_secondary' => 'IT',
	'unit_label' => 'House',
	'unit_count' => '3',
	'font_pairing' => 'classic',
	'color_bg' => '#f6f2ea',
	'color_surface' => '#fbf8f2',
	'color_ink' => '#2b2723',
	'color_muted' => '#7d7468',
	'color_line' => '#e6dfd2',
	'color_primary' => '#8a463f',
	'color_primary_deep' => '#6f3631',
	'color_primary_soft' => '#a8645a',
	'color_accent' => '#b47e6e',
	'color_gold' => '#a98c5b',
	'color_header' => '#8a463f',
	'color_header_deep' => '#73362f',
	'vat' => 'IT08825490728',
	'cin' => 'IT072019B400085362',
	'year' => '2026',
	'webdev' => array( 'label' => 'web dev logovia', 'url' => 'https://www.logovia.it/' ),
	'source_version' => '1.0.0',
	'source_build_date' => '2026-06-07',
);

$NAV = array(
	array( 'url' => 'index.php', 'label' => 'Home', 'key' => 'home' ),
	array( 'url' => 'villa.php', 'label' => 'Villa', 'key' => 'villa' ),
	array(
		'url' => 'houses.php',
		'label' => 'Houses',
		'key' => 'houses',
		'sub' => array(
			array( 'url' => 'house-for-2.php', 'label' => 'House for 2' ),
			array( 'url' => 'house-for-3.php', 'label' => 'House for 3' ),
			array( 'url' => 'house-for-4.php', 'label' => 'House for 4' ),
			array( 'url' => 'price-and-condition.php', 'label' => 'Price & Condition', 'divide' => true ),
		),
	),
	array( 'url' => 'spa-wellness.php', 'label' => 'SPA & Wellness', 'key' => 'spa' ),
	array( 'url' => 'experiences.php', 'label' => 'Experiences', 'key' => 'experiences' ),
	array( 'url' => 'surroundings.php', 'label' => 'Surroundings', 'key' => 'surroundings' ),
	array( 'url' => 'offers.php', 'label' => 'Offers', 'key' => 'offers' ),
	array( 'url' => 'contacts.php', 'label' => 'Contacts', 'key' => 'contacts' ),
);

$ICON = array(
	'pool' => '<path d="M2 17c2 0 2-1.5 4-1.5S10 17 12 17s2-1.5 4-1.5S20 17 22 17"/><path d="M2 21c2 0 2-1.5 4-1.5S10 21 12 21s2-1.5 4-1.5S20 21 22 21"/><path d="M8 13V5a2 2 0 0 1 4 0"/>',
	'park' => '<path d="M12 21v-7"/><circle cx="12" cy="9" r="6"/>',
	'spa' => '<path d="M12 3c2.5 3 4 5 4 7a4 4 0 0 1-8 0c0-2 1.5-4 4-7Z"/>',
	'wifi' => '<path d="M5 12.5a10 10 0 0 1 14 0"/><path d="M8 15.5a6 6 0 0 1 8 0"/><circle cx="12" cy="19" r="1"/>',
	'kitchen' => '<path d="M7 3v8M5 3v4a2 2 0 0 0 4 0V3M7 11v10"/><path d="M16 3c-1.5 1-2 3-2 5s.5 3 2 3 2-1 2-3-.5-4-2-5Zm0 8v10"/>',
	'bbq' => '<path d="M5 9h14l-1.5 6a2 2 0 0 1-2 1.5H8.5a2 2 0 0 1-2-1.5Z"/><path d="M9 9V7a3 3 0 0 1 6 0v2M10 19v2M14 19v2"/>',
	'car' => '<path d="M4 15l1.5-5A2 2 0 0 1 7.4 8.6h9.2A2 2 0 0 1 18.5 10L20 15"/><path d="M3 15h18v3H3z"/><circle cx="7" cy="18" r="1.4"/><circle cx="17" cy="18" r="1.4"/>',
	'gym' => '<path d="M3 9v6M6 7v10M18 7v10M21 9v6M6 12h12"/>',
	'bed' => '<path d="M3 11h18M5 11V7a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v4M4 11v7M20 11v7M4 15h16"/>',
	'ac' => '<path d="M12 2v20M3.4 7l17.2 10M20.6 7L3.4 17"/>',
);

$TEXT = array(
	'home' => 'Home',
	'houses' => 'Houses',
	'view_house' => 'View a House',
	'discover' => 'Discover',
	'discover_villa' => 'Discover the Villa',
	'discover_spa' => 'Discover the SPA',
	'explore_experiences' => 'Explore experiences',
	'show_all_photos' => 'Show all photos',
	'request_availability' => 'Request availability',
	'price_condition' => 'Price & condition',
	'contact_us' => 'Contact us',
	'contacts' => 'Contacts',
	'stay_in_touch' => 'Stay in touch',
	'privacy_policy' => 'Privacy Policy',
	'all_rights_reserved' => 'All rights reserved',
	'address' => 'Address',
	'phone' => 'Phone',
	'email' => 'Email',
	'open_maps' => 'Open in Google Maps ->',
	'chat_whatsapp' => 'Chat on WhatsApp',
	'form_name' => 'Name',
	'form_email' => 'Email',
	'form_phone' => 'Phone',
	'form_message' => 'Message',
	'form_name_placeholder' => 'Your name',
	'form_email_placeholder' => 'you@email.com',
	'form_phone_placeholder' => '+39 ...',
	'form_message_placeholder' => 'Tell us about your stay, dates and number of guests...',
	'form_send' => 'Send message',
	'form_result' => 'Thank you - this is a demo form. Connect it to your booking system or mailer.',
);

$C = array();

$C['home'] = array(
	'title' => 'Villa Rosa Resort - An Apulia Villa',
	'hero_over' => 'Villa Rosa Resort & SPA - Conversano',
	'hero_h1' => 'Your home in the<br/>heart of Puglia',
	'hero_sub' => 'An oasis of well-being nestled in a centuries-old park, steps from the Norman-Swabian Castle.',
	'scroll_label' => 'Scroll',
	'welcome_over' => 'Welcome',
	'welcome_h2' => 'An eclectic 1930s villa,<br/>reborn as a retreat',
	'welcome_p1' => 'Villa Rosa is your oasis of well-being. Nestled in a large park with centuries-old trees, just steps from the ancient Norman-Swabian Castle that characterizes the village of Conversano - one of Puglia\'s most charming villages - lies a complex of elegant residences, including a historic villa in an eclectic style from the 1930s.',
	'welcome_p2' => 'Every detail is designed for comfort: the privacy of our houses - each with a dining area, fully equipped kitchen, and outdoor pergola - the splendid pool, the gym, and the elegant spa.',
	'welcome_url' => 'villa.php',
	'welcome_stamp' => 'Since<br/>1930',
	'welcome_gallery' => array( $IMG['welcome'], $IMG['a1'], $IMG['a5'], $IMG['room'], $IMG['garden'] ),
	'houses_over' => 'The Houses',
	'houses_h2' => 'Your private retreat',
	'houses_p' => 'The new luxury in holidays is more freedom: an entire house with an external pergola at your disposal. Refined design, a mix of modern and ancient, and every comfort make the homes of Villa Rosa very exclusive.',
	'services_over' => 'Comfort & Care',
	'services_h2' => 'Services',
	'band_over' => 'The Apulian way of living',
	'band_h2' => 'Slow days, long tables,<br/>and the scent of the sea',
	'band_p' => 'From the whitewashed lanes of Conversano to the trulli of the Itria Valley and the turquoise coast - everything you love about Puglia begins at your doorstep.',
	'band_bg' => $IMG['apulian_table'],
	'spa_label' => 'Villa Rosa Resort & SPA',
	'spa_teaser_h3' => 'SPA & Wellness',
	'spa_teaser_p' => 'Awaken your mind and body. Our wellness center offers a hydromassage pool, Turkish bath, Finnish sauna, emotional hydroshower, relax area, gym, massages and a Yoga program.',
	'spa_teaser_url' => 'spa-wellness.php',
	'spa_gallery' => array( $IMG['jacuzzi_detail'], $IMG['room2'], $IMG['a5'], $IMG['garden'], $IMG['villa'] ),
	'experience_label' => 'Villa Rosa Resort & SPA',
	'experience_teaser_h3' => 'Apulian Experience',
	'experience_teaser_p' => 'We craft tailor-made experiences for each guest, customized according to individual needs - from cooking classes and wine tastings to private tours of the surrounding wonders.',
	'experience_teaser_url' => 'experiences.php',
	'experience_gallery' => array( $IMG['apulian_table'], $IMG['villa'], $IMG['welcome'], $IMG['a1'], $IMG['room'] ),
	'offers_over' => 'Villa Rosa offers',
	'offers_h2' => 'Summer Promotions',
	'offers_p' => 'Discover our seasonal offers and reserve your stay in the heart of Puglia at the very best conditions.',
	'offers_btn' => 'See the offers',
	'offers_url' => 'offers.php',
	'house_cta_over' => 'Your private retreat awaits',
	'house_cta_h2' => 'Choose your house<br/>in Villa Rosa',
	'house_cta_btn' => 'Explore the houses',
	'house_cta_url' => 'houses.php',
	'house_cta_bg' => $IMG['a1'],
);

$HOUSE_CARDS = array(
	array(
		'tag' => 'For 2 people',
		'title' => 'House for 2',
		'listing_title' => 'Houses for 2',
		'img' => $IMG['a1'],
		'gallery' => array( $IMG['room2'], $IMG['room'], $IMG['room_detail'] ),
		'url' => 'house-for-2.php',
		'specs' => array( array( 'Average surface', '30-40 m2' ), array( 'Maximum occupancy', '2 adults + 1 cot' ), array( 'Bed', 'King-size' ) ),
	),
	array(
		'tag' => 'For 3 people',
		'title' => 'House for 3',
		'listing_title' => 'Houses for 3',
		'img' => $IMG['room'],
		'gallery' => array( $IMG['room'], $IMG['room_detail'], $IMG['room2'] ),
		'url' => 'house-for-3.php',
		'specs' => array( array( 'Average surface', '40-50 m2' ), array( 'Maximum occupancy', '3 adults + 1 cot' ), array( 'Beds', 'King-size + sofa bed' ) ),
	),
	array(
		'tag' => 'For 4 people',
		'title' => 'House for 4',
		'listing_title' => 'Houses for 4',
		'img' => $IMG['room2'],
		'gallery' => array( $IMG['room_detail'], $IMG['room2'], $IMG['room'] ),
		'url' => 'house-for-4.php',
		'specs' => array( array( 'Average surface', '50-60 m2' ), array( 'Maximum occupancy', '4 adults + 1 cot' ), array( 'Beds', 'King-size + double sofa' ) ),
	),
);

$SERVICES = array(
	array( 'pool', 'Pool', 'Enjoy our pool in the green garden, perfect for relaxing and sunbathing.' ),
	array( 'park', 'Park', 'An oasis of tranquility, ideal for walks and moments of relaxation outdoors.' ),
	array( 'spa', 'SPA', 'Turkish bath, hot tub, sauna and massage room for a unique wellness experience.' ),
	array( 'wifi', 'Wi-Fi', 'To be, if you want, always reachable across the whole property.' ),
	array( 'kitchen', 'Equipped Kitchen', 'Each house has a full kitchen, to prepare your meals in complete independence.' ),
	array( 'bbq', 'BBQ', 'Our BBQ area in the park - the experience of grilling outdoors in style.' ),
	array( 'car', 'Car Rental', 'A car rental service, to enjoy every part of Puglia independently.' ),
	array( 'gym', 'Gym', 'To keep perfectly fit, even on holiday.' ),
);

$C['villa'] = array(
	'title' => 'Villa - Villa Rosa Resort',
	'over' => 'Villa Rosa Resort & SPA',
	'h1' => 'The Villa',
	'banner' => $IMG['villa'],
	'intro_over' => 'The luxury of feeling at home',
	'intro_h2' => 'On holiday,<br/>just like at home',
	'intro_p' => array(
		'Privacy, confidentiality, serenity and five-star comfort. The new luxury when it comes to holidays is giving yourself more freedom: the possibility of having an entire house at your disposal, to enjoy a fully relaxing stay.',
		'In the centre of the most beautiful Puglia, in the ancient heart of Conversano, in the park of a historic villa, having a house available is the ideal solution for those looking for a secluded, independent and even more exclusive stay.',
		'Attention to detail, refined design, a mix of modern and ancient, a stone\'s throw from monuments and shops - the houses of Villa Rosa, with private external pergolas, also offer the typical comforts of a resort.',
	),
	'gallery' => array( $IMG['a1'], $IMG['room'], $IMG['room2'], $IMG['a5'], $IMG['garden'], $IMG['villa'] ),
	'am_over' => 'Wellness, comfort & independence',
	'am_h2' => 'Every detail, designed for you',
	'am_p' => 'A wide range of services for your comfort and relaxation - all designed to guarantee maximum comfort and a truly unique experience.',
	'amenities' => array(
		array( 'spa', 'SPA & Wellness', 'Relax in our SPA with Turkish bath, sauna and massage room for a unique wellness experience.' ),
		array( 'pool', 'Outdoor Pool', 'Enjoy our swimming pool in the garden, perfect for relaxing and sunbathing.' ),
		array( 'park', 'Park & Garden', 'An oasis of tranquility, ideal for walks and moments of relaxation in the open air.' ),
		array( 'gym', 'Gym', 'A fully equipped gym to keep you fit even on holiday.' ),
		array( 'wifi', 'Free Wi-Fi', 'Free connection in all apartments and common areas.' ),
		array( 'kitchen', 'Equipped Kitchen', 'Each apartment has a complete kitchen to prepare your meals in complete independence.' ),
	),
	'cta_over' => 'Your private retreat awaits',
	'cta_h2' => 'Choose your house in Villa Rosa',
	'cta_btn' => 'Explore the houses',
	'cta_url' => 'houses.php',
	'cta_bg' => $IMG['a5'],
);

$C['houses'] = array(
	'title' => 'Houses - Villa Rosa Resort',
	'over' => 'Villa Rosa Resort',
	'h1' => 'Houses',
	'banner' => $IMG['welcome'],
	'intro_over' => 'Your private retreat in Puglia',
	'intro_h2' => 'An entire house, all to yourself',
	'intro_p' => 'The new luxury when it comes to holidays is giving yourself more freedom: the possibility of having an entire house with an external pergola at your disposal, to enjoy a fully relaxing stay. The attention to detail, a refined design, the mix of modern and ancient, and many comforts make the homes of Villa Rosa Boutique Resort very exclusive.',
	'cta_over' => 'Rates & reservations',
	'cta_h2' => 'Prices & conditions',
	'cta_p' => 'Transparent rates, flexible terms and a warm welcome. Discover everything you need to plan your stay.',
	'cta_btn' => 'View price & condition',
	'cta_url' => 'price-and-condition.php',
	'cta_bg' => $IMG['villa'],
);

$C['house2'] = array(
	'title' => 'Houses for 2 - Villa Rosa Resort',
	'over' => 'The Houses',
	'h1' => 'Houses for 2',
	'crumb_label' => 'For 2 people',
	'banner' => $IMG['welcome'],
	'main' => $IMG['a1'],
	'card_gallery' => array( $IMG['room2'], $IMG['room'], $IMG['room_detail'] ),
	'overview_gallery' => array( $IMG['room2'], $IMG['room_detail'], $IMG['room'] ),
	'intro_over' => 'Intimate & refined',
	'intro_h2' => 'A romantic retreat for two',
	'intro_p' => 'An elegant private house with its own external pergola - the perfect base for a couple\'s escape in the heart of Conversano. Refined design, the comfort of a five-star resort, and the freedom of a home of your own.',
	'specs' => array( array( 'Maximum occupancy', '2 adults + 1 baby cot' ) ),
	'listing_specs' => array( array( 'Average surface', '30-40 m2' ), array( 'Maximum occupancy', '2 adults + 1 cot' ), array( 'Bed', 'King-size' ) ),
	'gallery_over' => 'A look inside',
	'gallery_h2' => 'The room, in detail',
	'gallery' => array( $IMG['a1'], $IMG['room2'], $IMG['room'], $IMG['garden'], $IMG['a5'] ),
	'included_over' => 'What\'s included',
	'included_h2' => 'Comfort in every corner',
	'included' => array(
		array( 'kitchen', 'Equipped Kitchen', 'A complete kitchen with dining area for full independence.' ),
		array( 'bed', 'King-size Bed', 'A spacious king-size bed dressed in fine linens.' ),
		array( 'wifi', 'Free Wi-Fi', 'Fast, free connection throughout the house and grounds.' ),
		array( 'spa', 'SPA Access', 'Access to the wellness centre, pool and park.' ),
		array( 'ac', 'Air Conditioning', 'Independent climate control for the perfect temperature year-round.' ),
		array( 'car', 'Private Parking', 'Reserved on-site parking for a relaxed, stress-free arrival.' ),
	),
	'cta_over' => 'Ready when you are',
	'cta_h2' => 'Book your house for two',
	'cta_btn' => 'Request availability',
	'cta_url' => 'syncbooking:booking',
	'cta_bg' => $IMG['villa'],
);
$C['house3'] = array_replace( $C['house2'], array(
	'title' => 'Houses for 3 - Villa Rosa Resort',
	'h1' => 'Houses for 3',
	'crumb_label' => 'For 3 people',
	'banner' => $IMG['garden'],
	'main' => $IMG['room'],
	'card_gallery' => array( $IMG['room'], $IMG['room_detail'], $IMG['room2'] ),
	'overview_gallery' => array( $IMG['a5'] ),
	'intro_over' => 'Space for family or friends',
	'intro_h2' => 'Room to share, comfort to spare',
	'intro_p' => 'A generous private house with a king-size bed and an additional sofa bed, plus a private pergola for slow Apulian evenings. Ideal for a small family or three friends who want independence without giving up the comforts of a resort.',
	'specs' => array( array( 'Average surface', '40-50 m2' ), array( 'Maximum occupancy', '3 adults + 1 baby cot' ), array( 'Beds', 'King-size + sofa bed' ), array( 'Outdoor', 'Private pergola' ) ),
	'listing_specs' => array( array( 'Average surface', '40-50 m2' ), array( 'Maximum occupancy', '3 adults + 1 cot' ), array( 'Beds', 'King-size + sofa bed' ) ),
	'gallery' => array( $IMG['room'], $IMG['garden'], $IMG['a5'], $IMG['a1'], $IMG['room2'] ),
	'cta_h2' => 'Book houses for 3',
) );
$C['house4'] = array_replace( $C['house2'], array(
	'title' => 'Houses for 4 - Villa Rosa Resort',
	'h1' => 'Houses for 4',
	'crumb_label' => 'For 4 people',
	'banner' => $IMG['villa'],
	'main' => $IMG['room2'],
	'card_gallery' => array( $IMG['room_detail'], $IMG['room2'], $IMG['room'] ),
	'overview_gallery' => array( $IMG['garden'] ),
	'intro_over' => 'The whole family, at home',
	'intro_h2' => 'An entire home for four',
	'intro_p' => 'Our largest houses welcome up to four guests with a king-size bed and a double sofa bed, a fully equipped kitchen and a private external pergola. The ideal solution for a family holiday in total privacy and independence.',
	'specs' => array( array( 'Average surface', '50-60 m2' ), array( 'Maximum occupancy', '4 adults + 1 baby cot' ), array( 'Beds', 'King-size + double sofa bed' ), array( 'Outdoor', 'Private pergola' ) ),
	'listing_specs' => array( array( 'Average surface', '50-60 m2' ), array( 'Maximum occupancy', '4 adults + 1 cot' ), array( 'Beds', 'King-size + double sofa' ) ),
	'gallery' => array( $IMG['room2'], $IMG['a1'], $IMG['garden'], $IMG['room'], $IMG['a5'] ),
	'cta_h2' => 'Book houses for 4',
) );

$C['price'] = array(
	'title' => 'Price & Condition - Villa Rosa Resort',
	'over' => 'Rates & reservations',
	'h1' => 'Price & Condition',
	'banner' => $IMG['garden'],
	'intro_over' => 'Transparent & flexible',
	'intro_h2' => 'Plan your stay with confidence',
	'intro_p' => 'Check live availability and the best rates for each house, then confirm your reservation in a few secure steps - instant booking, no waiting for a reply.',
	'book_over' => 'Real-time availability',
	'book_h3' => 'Check dates & book online',
	'book_p' => 'Select your house, see live prices for your dates and complete your reservation through our secure booking system.',
	'book_btn' => 'Book your stay',
	'book_url' => 'syncbooking:booking',
	'book_note' => 'Best rate guaranteed when you book direct.',
	'cond_over' => 'Good to know',
	'cond_h2' => 'Conditions',
	'conditions' => array(
		array( 'Check-in', 'From 3:00 PM. Late arrivals can be arranged on request.' ),
		array( 'Check-out', 'By 10:30 AM on the day of departure.' ),
		array( 'Minimum stay', '2 nights; longer in high season and during special periods.' ),
		array( 'Included', 'Final cleaning, bed linen and towels, Wi-Fi, SPA, pool and park access.' ),
		array( 'City tax', 'Applied per person/night as required by the Municipality of Conversano.' ),
		array( 'Pets', 'Welcome on request - please let us know in advance.' ),
	),
	'cta_over' => 'Tailored to your dates',
	'cta_h2' => 'Request your personalised quote',
	'cta_btn' => 'Contact us',
	'cta_url' => 'contacts.php',
	'cta_bg' => $IMG['villa'],
);

$C['spa'] = array(
	'title' => 'SPA & Wellness - Villa Rosa Resort',
	'over' => 'Villa Rosa Resort & SPA',
	'h1' => 'SPA & Wellness',
	'banner' => $IMG['relax_lounge_detail'],
	'intro_over' => 'Awaken body & mind',
	'intro_h2' => 'A sanctuary<br/>of well-being',
	'intro_p' => array(
		'Dedicate time to yourself in our wellness centre, an intimate space designed for deep relaxation. Let the warmth of the Turkish bath, the heat of the Finnish sauna and the embrace of the hydromassage melt the day away.',
		'From emotional showers to a quiet relax area, every element is crafted to restore balance and leave you renewed - the perfect complement to your Apulian escape.',
	),
	'feat_rows' => array(
		array( 'label' => 'Water & heat', 'h3' => 'Hydromassage & Turkish bath', 'p' => 'Surrender to the warm jets of the hydromassage pool and the enveloping steam of the Turkish bath - a timeless ritual of relaxation.', 'gallery' => array( $IMG['spa_remote'], $IMG['garden'], $IMG['a5'] ) ),
		array( 'label' => 'Body & soul', 'h3' => 'Sauna, massages & Yoga', 'p' => 'Finnish sauna, emotional hydroshower, a serene relax area, expert massages and a dedicated Yoga program to reconnect with yourself.', 'gallery' => array( $IMG['garden'], $IMG['room2'], $IMG['villa'] ) ),
	),
	'am_over' => 'The wellness experience',
	'am_h2' => 'Everything for your relaxation',
	'amenities' => array(
		array( 'spa', 'Turkish Bath', 'Enveloping steam to purify body and mind.' ),
		array( 'spa', 'Finnish Sauna', 'Dry heat to release tension and restore energy.' ),
		array( 'pool', 'Hydromassage', 'Warm massaging jets for total relaxation.' ),
		array( 'wifi', 'Emotional Shower', 'Light, scent and water for a multisensory awakening.' ),
		array( 'park', 'Relax Area', 'A quiet space to rest between treatments.' ),
		array( 'gym', 'Gym & Yoga', 'A fitness space and a dedicated Yoga program.' ),
	),
	'cta_over' => 'Reserve your moment',
	'cta_h2' => 'Book your wellness experience',
	'cta_btn' => 'Contact us',
	'cta_url' => 'contacts.php',
	'cta_bg' => $IMG['sauna_detail'],
);

$C['experiences'] = array(
	'title' => 'Experiences - Villa Rosa Resort',
	'over' => 'Villa Rosa Resort & SPA',
	'h1' => 'Experiences',
	'banner' => $IMG['apulian_breakfast'],
	'intro_over' => 'Tailor-made for you',
	'intro_h2' => 'Live Puglia, your way',
	'intro_p' => 'We craft bespoke experiences for every guest, shaped around your tastes and curiosities. From the flavours of the Apulian table to the wonders just beyond our gates, let us design moments you will remember long after you leave.',
	'cards' => array(
		array( 'img' => $IMG['lunch'], 'over' => 'Taste', 'h3' => 'Cooking Classes', 'url' => 'post:cooking-classes' ),
		array( 'img' => $IMG['a5'], 'over' => 'Cellar', 'h3' => 'Wine Tastings', 'url' => 'post:wine-tastings' ),
		array( 'img' => $IMG['garden'], 'over' => 'Discover', 'h3' => 'Private Tours', 'url' => 'post:private-tours' ),
		array( 'img' => $IMG['villa'], 'over' => 'Sea', 'h3' => 'Coast & Beaches', 'url' => 'post:coast-beaches' ),
	),
	'wellness_over' => 'Body & soul',
	'wellness_h2' => 'Wellness & SPA',
	'wellness_p' => 'Tucked beneath ancient vaults, our wellness centre is a world apart: sauna, Turkish bath, emotional showers, a hydromassage pool and a candle-lit relaxation lounge - plus a fully equipped gym for those who like to keep moving.',
	'wellness_gallery' => array( $IMG['jacuzzi_detail'], $IMG['sauna_detail'], $IMG['turkish_bath_detail'], $IMG['relax_lounge_detail'], $IMG['gym_detail'] ),
	'band_over' => 'Unhurried & authentic',
	'band_h2' => 'The art of living,<br/>Apulian style',
	'band_p' => 'Long lunches under the pergola, sun-warmed stone, and the generous welcome of the South - this is the rhythm of a stay at Villa Rosa.',
	'band_bg' => $IMG['wellness_corridor'],
	'cta_over' => 'Design your days',
	'cta_h2' => 'Plan your experiences',
	'cta_btn' => 'Contact us',
	'cta_url' => 'contacts.php',
);

$C['surroundings'] = array(
	'title' => 'Surroundings - Villa Rosa Resort',
	'over' => 'Conversano & beyond',
	'h1' => 'Surroundings',
	'banner' => $IMG['conversano_town'],
	'intro_over' => 'In the heart of Puglia',
	'intro_h2' => 'A region to fall in love with',
	'intro_p' => 'Villa Rosa sits in the ancient heart of Conversano, one of Puglia\'s most charming villages, crowned by its Norman-Swabian Castle. From here, the wonders of the region are all within easy reach - whitewashed towns, the trulli of the Itria Valley, and the turquoise Adriatic coast.',
	'cards' => array(
		array( 'img' => $IMG['conversano_town'], 'over' => '2 min walk', 'h3' => 'Conversano', 'url' => 'post:conversano' ),
		array( 'img' => $IMG['villa'], 'over' => '25 min', 'h3' => 'Polignano a Mare', 'url' => 'post:polignano-a-mare' ),
		array( 'img' => $IMG['a5'], 'over' => '35 min', 'h3' => 'Alberobello & Itria Valley', 'url' => 'post:alberobello-itria-valley' ),
		array( 'img' => $IMG['welcome'], 'over' => '40 min', 'h3' => 'Bari', 'url' => 'post:bari' ),
	),
	'cta_over' => 'Let us guide you',
	'cta_h2' => 'Discover Puglia with us',
	'cta_btn' => 'See our experiences',
	'cta_url' => 'experiences.php',
	'cta_bg' => $IMG['villa'],
);

$C['offers'] = array(
	'title' => 'Offers - Villa Rosa Resort',
	'over' => 'Villa Rosa offers',
	'h1' => 'Offers',
	'banner' => $IMG['villa'],
	'intro_over' => 'Best available conditions',
	'intro_h2' => 'Seasonal promotions',
	'intro_p' => 'Reserve your stay in the heart of Puglia at the very best conditions. Discover our current offers - and contact us directly for exclusive, tailor-made rates.',
	'cards' => array(
		array( 'img' => $IMG['a5'], 'badge' => 'Early booking', 'h3' => 'Book Early, Save More', 'p' => 'Reserve well in advance and enjoy a special rate on your favourite house.', 'url' => 'post:book-early-save-more' ),
		array( 'img' => $IMG['garden'], 'badge' => 'Long stay', 'h3' => '7 Nights = 6', 'p' => 'Stay a week and pay for six nights - the perfect way to truly unwind in Puglia.', 'url' => 'post:seven-nights-six' ),
		array( 'img' => $IMG['jacuzzi_detail'], 'badge' => 'Wellness', 'h3' => 'SPA Escape', 'p' => 'A romantic stay for two with a dedicated wellness experience in our SPA.', 'url' => 'post:spa-escape' ),
		array( 'img' => $IMG['villa'], 'badge' => 'Season', 'h3' => 'Spring & Autumn', 'p' => 'Discover Puglia in its gentlest seasons with our reduced shoulder-season rates.', 'url' => 'post:spring-autumn' ),
	),
	'cta_over' => 'Tailored to you',
	'cta_h2' => 'Ask for your best rate',
	'cta_btn' => 'Contact us',
	'cta_url' => 'contacts.php',
	'cta_bg' => $IMG['a5'],
);

$C['contacts'] = array(
	'title' => 'Contacts - Villa Rosa Resort',
	'over' => 'We are here for you',
	'h1' => 'Contacts',
	'banner' => $IMG['welcome'],
	'intro_over' => 'Get in touch',
	'intro_h2' => 'Plan your stay with us',
	'intro_p' => 'For availability, tailored quotes or any request, our team will be delighted to help. Reach us by phone, email or WhatsApp - or send a message using the form and we will reply as soon as possible.',
);

$C['article'] = array(
	'title' => 'Article - Villa Rosa Resort',
	'over' => 'Villa Rosa Resort & SPA',
	'h1' => 'Experiences',
	'banner' => $IMG['lunch'],
	'article_over' => 'Taste',
	'article_title' => 'Cooking Classes in the heart of Puglia',
	'article_meta' => 'Experiences - 5 min read',
	'body_p1' => 'Write your article here. This opening paragraph sets the scene - the drop-cap is applied automatically, so simply start typing and let the words lead your guest into the story. Replace this text with your own.',
	'body_p2' => 'Continue with the body of your article. You can write as many paragraphs as you like; each one will flow in this comfortable, readable column. Talk about the experience, what guests will see, taste and feel, and why it matters.',
	'body_h2' => 'A section heading',
	'body_p3' => 'Use headings to break longer pieces into clear sections. This makes the article easy to scan and pleasant to read on any device.',
	'body_quote' => 'Add a short, evocative quote here to give the page a moment of pause.',
	'body_h3' => 'A smaller subheading',
	'body_p4' => 'You can also use bulleted lists to highlight practical details:',
	'body_items' => array( 'First point - for example, what is included', 'Second point - duration, group size or location', 'Third point - anything else worth noting' ),
	'body_p5' => 'Close with a final thought or an invitation. When you are ready, guests can',
	'body_link_label' => 'get in touch',
	'body_link_url' => 'contacts.php',
	'cta_over' => 'Design your days',
	'cta_h2' => 'Plan your experiences',
	'cta_btn' => 'Contact us',
	'cta_url' => 'contacts.php',
	'cta_bg' => $IMG['a5'],
);

if ( function_exists( 'sbt_bootstrap_content' ) ) {
	sbt_bootstrap_content( $IMG, $SITE, $NAV, $C, $HOUSE_CARDS, $SERVICES, $TEXT );
}
