<?php
/* Theme 03 - Masseria Montefieno. Rebuilt from clean HTML source 3.0. */

$BASE = function_exists( 'sbt_media_base_url' ) ? rtrim( sbt_media_base_url(), '/' ) : 'assets';

if ( ! function_exists( 'sbt_t3_asset' ) ) {
	function sbt_t3_asset( $path ) {
		return function_exists( 'sbt_asset_url' ) ? sbt_asset_url( $path ) : $path;
	}
}

$IMG = array(
	'favicon'   => sbt_t3_asset( 'assets/images/logo.png' ),
	'logo'      => sbt_t3_asset( 'assets/images/logo.png' ),
	'logo_foot' => sbt_t3_asset( 'assets/images/logo.png' ),
	'welcome'   => sbt_t3_asset( 'assets/images/mf-05.jpg' ),
	'hero_1'    => sbt_t3_asset( 'assets/images/mf-05.jpg' ),
	'hero_2'    => sbt_t3_asset( 'assets/images/mf-12.jpg' ),
	'hero_3'    => sbt_t3_asset( 'assets/images/mf-16.jpg' ),
	'hero_4'    => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
	'band'      => sbt_t3_asset( 'assets/images/mf-25.jpg' ),
	'whole'     => sbt_t3_asset( 'assets/images/mf-05.jpg' ),
	'room_main' => sbt_t3_asset( 'assets/images/mf-10.jpg' ),
	'pool'      => sbt_t3_asset( 'assets/images/mf-12.jpg' ),
	'farm'      => sbt_t3_asset( 'assets/images/mf-27.jpg' ),
	'surr_hero' => sbt_t3_asset( 'assets/images/mf-25.jpg' ),
	'contacts_hero' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
);

$SITE = array(
	'name' => 'Masseria Montefieno',
	'tagline' => 'A stunning Masseria in Puglia',
	'address' => 'Contrada Montefieno<br/>70014 Conversano (Bari)<br/>Puglia, Italy',
	'address_line_1' => 'Contrada Montefieno',
	'address_line_2' => '70014 Conversano (Bari)',
	'address_line_3' => 'Puglia, Italy',
	'phone1' => '+39 338 250 7545',
	'phone1_t' => '+393382507545',
	'phone2' => '+39 320 609 0558',
	'phone2_t' => '+393206090558',
	'email' => 'info@masserialecerase.com',
	'wa' => 'https://wa.me/393382507545',
	'facebook' => 'https://www.facebook.com/masserialecerase/',
	'instagram' => 'https://www.instagram.com/masseria_lecerase_montefieno/',
	'lang_primary' => 'EN',
	'lang_secondary' => 'IT',
	'rental_mode' => 'units',
	'entire_label' => 'Entire Masseria',
	'unit_label' => 'Room',
	'unit_count' => '3',
	'whatsapp_label' => 'WhatsApp',
	'font_pairing' => 'classic',
	'color_bg' => '#f4efe5',
	'color_surface' => '#faf6ee',
	'color_ink' => '#2b2723',
	'color_muted' => '#7d7468',
	'color_line' => '#e3dbcf',
	'color_primary' => '#8f6f45',
	'color_primary_deep' => '#6f5734',
	'color_primary_soft' => '#aa8758',
	'color_accent' => '#8f6f45',
	'color_gold' => '#a98c5b',
	'color_header' => '#8f6f45',
	'color_header_deep' => '#6f5734',
	'map' => 'https://maps.google.com/?q=Masseria+Montefieno+Conversano',
	'map_embed' => '',
	'year' => '2026',
	'vat' => 'IT08825490728',
	'cin' => 'IT072019B400085362',
	'webdev' => array( 'label' => 'SyncBooking', 'url' => 'https://syncbooking.com' ),
	'source_version' => '4.0',
	'source_build_date' => '2026-06-14',
);

$NAV = array(
	array( 'key' => 'home', 'label' => 'Home', 'url' => 'index.php' ),
	array( 'key' => 'villa', 'label' => 'Masseria', 'url' => 'villa.php' ),
	array(
		'key' => 'house',
		'label' => 'Accomodation',
		'url' => 'house.php',
		'sub' => array(
			array( 'label' => 'Rooms', 'desc' => 'Rooms only', 'url' => 'house.php' ),
			array( 'label' => 'The whole Masseria', 'desc' => 'Exclusive rental', 'url' => 'whole-masseria.php' ),
			array( 'label' => 'Price & Condition', 'desc' => 'Rates, check-in & terms', 'url' => 'price-and-condition.php', 'divide' => true ),
			array( 'label' => 'Book Now', 'desc' => 'Online booking', 'url' => 'syncbooking:booking' ),
		),
	),
	array( 'key' => 'pool', 'label' => 'Pool', 'url' => 'pool.php' ),
	array( 'key' => 'farm', 'label' => 'Farm', 'url' => 'farm.php' ),
	array( 'key' => 'surroundings', 'label' => 'Surroundings', 'url' => 'surroundings.php' ),
	array( 'key' => 'contacts', 'label' => 'Contacts', 'url' => 'contacts.php' ),
);

$ICON = array(
	'pool' => '<path d="M2 17c2 0 2-1.5 4-1.5S10 17 12 17s2-1.5 4-1.5S20 17 22 17"/><path d="M2 21c2 0 2-1.5 4-1.5S10 21 12 21s2-1.5 4-1.5S20 21 22 21"/><path d="M8 13V5a2 2 0 0 1 4 0"/>',
	'tree' => '<path d="M12 21v-7"/><circle cx="12" cy="9" r="6"/>',
	'kitchen' => '<path d="M7 3v8M5 3v4a2 2 0 0 0 4 0V3M7 11v10"/><path d="M16 3c-1.5 1-2 3-2 5s.5 3 2 3 2-1 2-3-.5-4-2-5Zm0 8v10"/>',
	'wifi' => '<path d="M5 12.5a10 10 0 0 1 14 0"/><path d="M8 15.5a6 6 0 0 1 8 0"/><circle cx="12" cy="19" r="1"/>',
	'bbq' => '<path d="M5 9h14l-1.5 6a2 2 0 0 1-2 1.5H8.5a2 2 0 0 1-2-1.5Z"/><path d="M9 9V7a3 3 0 0 1 6 0v2M10 19v2M14 19v2"/>',
	'bed' => '<path d="M3 11h18M5 11V7a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v4M4 11v7M20 11v7M4 15h16"/>',
	'home' => '<path d="M4 21V8l8-5 8 5v13M9 21v-6h6v6"/>',
	'pin' => '<circle cx="12" cy="11" r="3"/><path d="M12 2a8 8 0 0 1 8 8c0 5.4-8 12-8 12S4 15.4 4 10a8 8 0 0 1 8-8Z"/>',
);

$TEXT = array(
	'home' => 'Home',
	'houses' => 'Rooms',
	'discover' => 'Discover',
	'show_all_photos' => 'Show all photos',
	'request_availability' => 'Request availability',
	'price_condition' => 'Price & condition',
	'contacts' => 'Contacts',
	'stay_in_touch' => 'Stay in touch',
	'privacy_policy' => 'Privacy Policy',
	'all_rights_reserved' => 'All rights reserved',
	'address' => 'Address',
	'phone' => 'Phone',
	'email' => 'Email',
	'open_maps' => 'Open in Google Maps ->',
	'chat_whatsapp' => 'Chat on WhatsApp',
	'form_name' => 'Name',
	'form_email' => 'Email',
	'form_phone' => 'Phone',
	'form_message' => 'Message',
	'form_name_placeholder' => 'Your name',
	'form_email_placeholder' => 'you@email.com',
	'form_phone_placeholder' => '+39 ...',
	'form_message_placeholder' => 'Tell us about your stay, dates and number of guests...',
	'form_send' => 'Send message',
	'form_result' => 'Thank you - your request has been sent. We will contact you shortly.',
);

$GALLERY = array(
	sbt_t3_asset( 'assets/images/mf-03.jpg' ),
	sbt_t3_asset( 'assets/images/mf-10.jpg' ),
	sbt_t3_asset( 'assets/images/mf-01.jpg' ),
	sbt_t3_asset( 'assets/images/mf-16.jpg' ),
	sbt_t3_asset( 'assets/images/mf-12.jpg' ),
);

$SERVICES = array(
	array( 'pool', 'Pool', 'A pool set among the centuries-old olive trees, with loungers and large pool towels provided.' ),
	array( 'tree', 'Olive Groves', 'Seven hectares of old olive trees and fruit trees to wander, in complete silence.' ),
	array( 'kitchen', 'Two Kitchens', 'Fully equipped with fridge, dishwasher, oven and hob, coffee machine, toaster and tea.' ),
	array( 'wifi', 'Wi-Fi', 'Connectivity across the estate, for whenever you need it.' ),
	array( 'bbq', 'Outdoor Areas', 'Three outdoor areas around the main house, including a pergola for long meals in the shade.' ),
	array( 'bed', 'Linen & Towels', 'Bed linen plus a small, medium and large towel per person, and a professional hairdryer in each bathroom.' ),
	array( 'home', 'Laundry', 'Washing machine, ironing board and clothes hanger at your disposal.' ),
	array( 'pin', 'Strategic Location', 'In the middle of Polignano, Conversano and Castellana Grotte, 15 minutes from Alberobello.' ),
);

$HOUSE_CARDS = array(
	array(
		'tag' => 'Sleep',
		'title' => 'Bedrooms',
		'listing_title' => 'Bedrooms',
		'img' => sbt_t3_asset( 'assets/images/mf-10.jpg' ),
		'gallery' => array( sbt_t3_asset( 'assets/images/mf-10.jpg' ), sbt_t3_asset( 'assets/images/mf-24.jpg' ), sbt_t3_asset( 'assets/images/mf-14.jpg' ) ),
		'url' => 'rooms.php',
		'specs' => array( array( 'Rooms', '4 bedrooms' ), array( 'Style', 'Stone vaults' ), array( 'View', 'Countryside' ) ),
	),
	array(
		'tag' => 'Exclusive use',
		'title' => 'The Whole Masseria',
		'listing_title' => 'Whole Masseria',
		'img' => sbt_t3_asset( 'assets/images/mf-05.jpg' ),
		'gallery' => array( sbt_t3_asset( 'assets/images/mf-05.jpg' ), sbt_t3_asset( 'assets/images/mf-09.jpg' ), sbt_t3_asset( 'assets/images/mf-17.jpg' ) ),
		'url' => 'whole-masseria.php',
		'specs' => array( array( 'Use', 'Exclusive' ), array( 'Outdoors', 'Three areas' ), array( 'Pool', 'Private' ) ),
	),
	array(
		'tag' => 'Outdoors',
		'title' => 'Pool',
		'listing_title' => 'Pool',
		'img' => sbt_t3_asset( 'assets/images/mf-12.jpg' ),
		'gallery' => array( sbt_t3_asset( 'assets/images/mf-12.jpg' ), sbt_t3_asset( 'assets/images/mf-18.jpg' ), sbt_t3_asset( 'assets/images/mf-20.jpg' ) ),
		'url' => 'pool.php',
		'specs' => array( array( 'Setting', 'Olive trees' ), array( 'Comfort', 'Loungers' ), array( 'Towels', 'Included' ) ),
	),
);

$C = array(
	'home' => array(
		'title' => 'Masseria Montefieno - A stunning Masseria in Puglia',
		'hero_over' => 'Masseria Montefieno · Conversano · Puglia',
		'hero_h1' => 'Silence, stillness,<br/>and ancient olives',
		'hero_sub' => 'A masseria in the Puglia countryside, surrounded by seven hectares of centuries-old olive groves and fruit trees.',
		'hero_slides' => array( $IMG['hero_1'], $IMG['hero_2'], $IMG['hero_3'], $IMG['hero_4'] ),
		'scroll_label' => 'Scroll',
		'welcome_over' => 'Welcome',
		'welcome_h2' => 'An idyllic corner<br/>of the Puglia countryside',
		'welcome_p1' => 'Masseria Montefieno sits in an idyllic location in the Puglia countryside, surrounded by seven hectares of picturesque farmland of old olive trees and a selection of fruit trees. Everywhere, silence and stillness.',
		'welcome_p2' => 'Each room has been inspired by the elegance of the simple traditions of Puglia, with magnificent views over the surrounding countryside.',
		'welcome_url' => 'villa.php',
		'welcome_gallery' => array( sbt_t3_asset( 'assets/images/mf-05.jpg' ), sbt_t3_asset( 'assets/images/mf-04.jpg' ), sbt_t3_asset( 'assets/images/mf-08.jpg' ), sbt_t3_asset( 'assets/images/mf-02.jpg' ), sbt_t3_asset( 'assets/images/mf-22.jpg' ) ),
		'welcome_stamp' => 'Seven<br/>hectares',
		'gallery_over' => 'A look inside',
		'gallery_h2' => 'Stone, light and tradition',
		'gallery' => $GALLERY,
		'houses_over' => 'The estate',
		'houses_h2' => 'Two houses among the olives',
		'houses_p' => 'The main structure offers three beautifully restored stone bedrooms with decoration typical of Puglia, two kitchens, three bathrooms, a large living room and three outdoor areas. A second house, 120 metres away, adds one more bedroom with its own bathroom and outdoor space.',
		'services_over' => 'Comfort & Care',
		'services_h2' => 'The estate at your service',
		'band_bg' => sbt_t3_asset( 'assets/images/mf-25.jpg' ),
		'band_over' => 'In the heart of Puglia',
		'band_h2' => 'Between Polignano, Conversano<br/>and Castellana Grotte',
		'band_p' => 'Fifteen minutes from the trulli of Alberobello, the beaches of Monopoli and the Itria Valley.',
		'farm_label' => 'Masseria Montefieno',
		'farm_h3' => 'The Farm',
		'farm_p' => 'The masseria is a working farm: extra-virgin olive oil from the centuries-old grove and Vitus Primitivo wine from our vineyards.',
		'farm_url' => 'farm.php',
		'farm_gallery' => array( sbt_t3_asset( 'assets/images/mf-27.jpg' ), sbt_t3_asset( 'assets/images/mf-21.jpg' ), sbt_t3_asset( 'assets/images/mf-11.jpg' ), sbt_t3_asset( 'assets/images/mf-13.jpg' ) ),
		'surroundings_label' => 'Masseria Montefieno',
		'surroundings_h3' => 'The Surroundings',
		'surroundings_p' => 'The complex sits at a strategic point for travellers, in the middle of Polignano a Mare, Conversano and Castellana Grotte.',
		'surroundings_url' => 'surroundings.php',
		'surroundings_gallery' => array( sbt_t3_asset( 'assets/images/mf-25.jpg' ), sbt_t3_asset( 'assets/images/mf-26.jpg' ), sbt_t3_asset( 'assets/images/mf-21.jpg' ) ),
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
		'cta_over' => 'Silence and stillness await',
		'cta_h2' => 'Your stay at<br/>Masseria Montefieno',
		'cta_p' => '',
		'cta_btn' => 'Discover the stay',
		'cta_url' => 'whole-masseria.php',
	),
	'villa' => array(
		'title' => 'The Masseria - Masseria Montefieno',
		'over' => 'Masseria Montefieno',
		'h1' => 'The Masseria',
		'banner' => sbt_t3_asset( 'assets/images/mf-05.jpg' ),
		'intro_over' => 'Restored stone, Apulian soul',
		'intro_h2' => 'Everywhere,<br/>silence and stillness',
		'intro_p' => 'The main structure offers beautifully restored stone rooms, kitchens, outdoor spaces and silence among seven hectares of olives and fruit trees.',
		'gallery' => array( sbt_t3_asset( 'assets/images/mf-05.jpg' ), sbt_t3_asset( 'assets/images/mf-04.jpg' ), sbt_t3_asset( 'assets/images/mf-08.jpg' ), sbt_t3_asset( 'assets/images/mf-16.jpg' ), sbt_t3_asset( 'assets/images/mf-22.jpg' ) ),
		'cta_over' => 'Stay in Montefieno',
		'cta_h2' => 'Plan your stay',
		'cta_btn' => 'Request availability',
		'cta_url' => 'syncbooking:booking',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
	),
	'house' => array(
		'title' => 'Bedrooms - Masseria Montefieno',
		'over' => 'Rooms',
		'h1' => 'Bedrooms',
		'banner' => sbt_t3_asset( 'assets/images/mf-10.jpg' ),
		'intro_over' => 'Intimate & refined',
		'intro_h2' => 'Sleeping in restored stone',
		'intro_p' => 'Each room has been inspired by the elegance of simple traditions, with views over the surrounding countryside.',
		'gallery' => array( sbt_t3_asset( 'assets/images/mf-10.jpg' ), sbt_t3_asset( 'assets/images/mf-24.jpg' ), sbt_t3_asset( 'assets/images/mf-14.jpg' ) ),
		'overview_gallery' => array( sbt_t3_asset( 'assets/images/mf-10.jpg' ), sbt_t3_asset( 'assets/images/mf-24.jpg' ), sbt_t3_asset( 'assets/images/mf-14.jpg' ) ),
		'specs' => array( array( 'Rooms', '4 bedrooms' ), array( 'Bathrooms', '4 bathrooms' ), array( 'View', 'Countryside' ) ),
		'cta_over' => 'Ready when you are',
		'cta_h2' => 'Book your room',
		'cta_btn' => 'Request availability',
		'cta_url' => 'syncbooking:booking',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-10.jpg' ),
	),
	'whole' => array(
		'title' => 'The Whole Masseria - Masseria Montefieno',
		'over' => 'Exclusive use',
		'h1' => 'The Whole Masseria',
		'banner' => sbt_t3_asset( 'assets/images/mf-05.jpg' ),
		'intro_over' => 'One booking, the entire estate',
		'intro_h2' => 'The masseria, yours alone',
		'intro_p' => 'Reserve the main house, the second house, the pool and all outdoor areas for your party.',
		'gallery' => array( sbt_t3_asset( 'assets/images/mf-05.jpg' ), sbt_t3_asset( 'assets/images/mf-09.jpg' ), sbt_t3_asset( 'assets/images/mf-17.jpg' ), sbt_t3_asset( 'assets/images/mf-12.jpg' ) ),
		'cta_over' => 'Exclusive stay',
		'cta_h2' => 'Request availability',
		'cta_btn' => 'Book now',
		'cta_url' => 'syncbooking:booking',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
	),
	'pool' => array(
		'title' => 'The Pool - Masseria Montefieno',
		'over' => 'Outdoors',
		'h1' => 'The Pool',
		'banner' => sbt_t3_asset( 'assets/images/mf-12.jpg' ),
		'intro_over' => 'Water and silver leaves',
		'intro_h2' => 'A pool set<br/>in the olive grove',
		'intro_p' => 'A pool set among centuries-old olive trees, with loungers and large pool towels provided.',
		'gallery' => array( sbt_t3_asset( 'assets/images/mf-12.jpg' ), sbt_t3_asset( 'assets/images/mf-18.jpg' ), sbt_t3_asset( 'assets/images/mf-20.jpg' ) ),
		'cta_over' => 'Relax outdoors',
		'cta_h2' => 'Plan your stay',
		'cta_btn' => 'Request availability',
		'cta_url' => 'syncbooking:booking',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-12.jpg' ),
	),
	'farm' => array(
		'title' => 'The Farm - Masseria Montefieno',
		'over' => 'The Farm',
		'h1' => 'The Farm',
		'banner' => sbt_t3_asset( 'assets/images/mf-27.jpg' ),
		'intro_over' => 'A working estate',
		'intro_h2' => 'Old olives, fruit trees, vines',
		'intro_p' => 'Extra-virgin olive oil from the centuries-old grove and Vitus Primitivo wine from the vineyards, made in the traditions of this corner of Puglia.',
		'gallery' => array( sbt_t3_asset( 'assets/images/mf-27.jpg' ), sbt_t3_asset( 'assets/images/mf-21.jpg' ), sbt_t3_asset( 'assets/images/mf-11.jpg' ), sbt_t3_asset( 'assets/images/mf-13.jpg' ) ),
		'cta_over' => 'Taste the land',
		'cta_h2' => 'Discover Montefieno',
		'cta_btn' => 'Contact us',
		'cta_url' => 'contacts.php',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-27.jpg' ),
	),
	'price' => array(
		'title' => 'Price & Condition - Masseria Montefieno',
		'over' => 'Price & Condition',
		'h1' => 'Price & Condition',
		'banner' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
		'intro_over' => 'Clear terms',
		'intro_h2' => 'Plan your stay<br/>with clarity',
		'intro_p' => 'Rates and conditions vary by season, length of stay and booking formula.',
		'cta_over' => 'Ready when you are',
		'cta_h2' => 'Request availability',
		'cta_btn' => 'Book now',
		'cta_url' => 'syncbooking:booking',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
	),
	'surroundings' => array(
		'title' => 'Surroundings - Masseria Montefieno',
		'over' => 'Surroundings',
		'h1' => 'Surroundings',
		'banner' => sbt_t3_asset( 'assets/images/mf-25.jpg' ),
		'intro_over' => 'Strategic location',
		'intro_h2' => 'Between Polignano,<br/>Conversano and Castellana',
		'intro_p' => 'A strategic point for travellers, close to Alberobello, Monopoli, the Itria Valley and the most representative towns of Puglia.',
		'gallery' => array( sbt_t3_asset( 'assets/images/mf-25.jpg' ), sbt_t3_asset( 'assets/images/mf-26.jpg' ), sbt_t3_asset( 'assets/images/mf-21.jpg' ) ),
		'cta_over' => 'Explore Puglia',
		'cta_h2' => 'Start from Montefieno',
		'cta_btn' => 'Contact us',
		'cta_url' => 'contacts.php',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-25.jpg' ),
	),
	'contacts' => array(
		'title' => 'Contacts - Masseria Montefieno',
		'over' => 'Contacts',
		'h1' => 'Contacts',
		'banner' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
		'intro_over' => 'Write to us',
		'intro_h2' => 'Plan your stay',
		'intro_p' => 'For availability, quotes or special requests, we will be happy to help.',
	),
);

if ( function_exists( 'sbt_bootstrap_content' ) ) {
	sbt_bootstrap_content( $IMG, $SITE, $NAV, $C, $HOUSE_CARDS, $SERVICES, $TEXT, $GALLERY );
}
