<?php
/* Theme 03 - Masseria Montefieno. Rebuilt from clean HTML source 3.0. */

$BASE = function_exists( 'sbt_media_base_url' ) ? rtrim( sbt_media_base_url(), '/' ) : 'assets';

if ( ! function_exists( 'sbt_t3_asset' ) ) {
	function sbt_t3_asset( $path ) {
		return function_exists( 'sbt_asset_url' ) ? sbt_asset_url( $path ) : $path;
	}
}

$IMG = array(
	'favicon'   => sbt_t3_asset( 'assets/favicon.png' ),
	'logo'      => sbt_t3_asset( 'assets/images/logo.png' ),
	'logo_foot' => sbt_t3_asset( 'assets/images/logo.png' ),
	'welcome'   => sbt_t3_asset( 'assets/images/mf-05.jpg' ),
	'hero_1'    => sbt_t3_asset( 'assets/images/mf-05.jpg' ),
	'hero_2'    => sbt_t3_asset( 'assets/images/mf-12.jpg' ),
	'hero_3'    => sbt_t3_asset( 'assets/images/mf-16.jpg' ),
	'hero_4'    => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
	'band'      => sbt_t3_asset( 'assets/images/mf-25.jpg' ),
	'whole'     => sbt_t3_asset( 'assets/images/mf-05.jpg' ),
	'room_main' => sbt_t3_asset( 'assets/images/mf-10.jpg' ),
	'pool'      => sbt_t3_asset( 'assets/images/mf-12.jpg' ),
	'farm'      => sbt_t3_asset( 'assets/images/mf-27.jpg' ),
	'surr_hero' => sbt_t3_asset( 'assets/images/mf-25.jpg' ),
	'contacts_hero' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
);

$SITE = array(
	'name' => 'Masseria Montefieno',
	'tagline' => 'A stunning Masseria in Puglia',
	'logo_class' => 'sbtw-logo-txt',
	'logo_html' => '<img class="sbtw-lg-w" src="' . esc_url( sbt_t3_asset( 'assets/images/logo-montefieno-white.png' ) ) . '" alt="Masseria Montefieno" /><img class="sbtw-lg-d" src="' . esc_url( sbt_t3_asset( 'assets/images/logo-montefieno-dark.png' ) ) . '" alt="Masseria Montefieno" />',
	'logo_foot_class' => 'sbtw-logo-txt sbtw-logo-foot',
	'logo_foot_html' => '<img src="' . esc_url( sbt_t3_asset( 'assets/images/logo-montefieno.png' ) ) . '" alt="Masseria Montefieno" />',
	'address' => 'Contrada Montefieno<br/>70014 Conversano (Bari)<br/>Puglia, Italy',
	'address_line_1' => 'Contrada Montefieno',
	'address_line_2' => '70014 Conversano (Bari)',
	'address_line_3' => 'Puglia, Italy',
	'phone1' => '+39 338 250 7545',
	'phone1_t' => '+393382507545',
	'phone2' => '+39 320 609 0558',
	'phone2_t' => '+393206090558',
	'email' => 'info@masserialecerase.com',
	'wa' => 'https://wa.me/393382507545',
	'facebook' => 'https://www.facebook.com/masserialecerase/',
	'instagram' => 'https://www.instagram.com/masseria_lecerase_montefieno/',
	'lang_primary' => 'EN',
	'lang_secondary' => 'IT',
	'rental_mode' => 'entire',
	'entire_label' => 'Entire Masseria',
	'unit_label' => 'Room',
	'unit_count' => '3',
	'whatsapp_label' => 'WhatsApp',
	'font_pairing' => 'classic',
	'color_bg' => '#f4efe5',
	'color_surface' => '#faf6ee',
	'color_ink' => '#2b2723',
	'color_muted' => '#7d7468',
	'color_line' => '#e3dbcf',
	'color_primary' => '#8f6f45',
	'color_primary_deep' => '#6f5734',
	'color_primary_soft' => '#aa8758',
	'color_accent' => '#8f6f45',
	'color_gold' => '#a98c5b',
	'color_header' => '#8f6f45',
	'color_header_deep' => '#6f5734',
	'map' => 'https://maps.google.com/?q=Masseria+Montefieno+Conversano',
	'map_embed' => '',
	'year' => '2026',
	'vat' => 'IT08825490728',
	'cin' => 'IT072019B400085362',
	'webdev' => array( 'label' => 'SyncBooking', 'url' => 'https://syncbooking.com' ),
	'source_version' => '5.0',
	'source_build_date' => '2026-06-16',
);

$NAV = array(
	array( 'key' => 'home', 'label' => 'Home', 'url' => 'index.php' ),
	array( 'key' => 'villa', 'label' => 'Masseria', 'url' => 'villa.php' ),
	array(
		'key' => 'house',
		'label' => 'Accommodation',
		'url' => 'house.php',
		'sub' => array(
			array( 'label' => 'Rooms', 'desc' => 'Rooms only', 'url' => 'house.php' ),
			array( 'label' => 'The whole Masseria', 'desc' => 'Exclusive rental', 'url' => 'whole-masseria.php' ),
			array( 'label' => 'Price & Condition', 'desc' => 'Rates, check-in & terms', 'url' => 'price-and-condition.php', 'divide' => true ),
			array( 'label' => 'Book Now', 'desc' => 'Online booking', 'url' => 'syncbooking:booking', 'book' => true ),
		),
	),
	array( 'key' => 'pool', 'label' => 'Pool', 'url' => 'pool.php' ),
	array( 'key' => 'farm', 'label' => 'Farm', 'url' => 'farm.php' ),
	array( 'key' => 'surroundings', 'label' => 'Surroundings', 'url' => 'surroundings.php' ),
	array( 'key' => 'contacts', 'label' => 'Contacts', 'url' => 'contacts.php' ),
);

$ICON = array(
	'pool' => '<path d="M2 17c2 0 2-1.5 4-1.5S10 17 12 17s2-1.5 4-1.5S20 17 22 17"/><path d="M2 21c2 0 2-1.5 4-1.5S10 21 12 21s2-1.5 4-1.5S20 21 22 21"/><path d="M8 13V5a2 2 0 0 1 4 0"/>',
	'tree' => '<path d="M12 21v-7"/><circle cx="12" cy="9" r="6"/>',
	'kitchen' => '<path d="M7 3v8M5 3v4a2 2 0 0 0 4 0V3M7 11v10"/><path d="M16 3c-1.5 1-2 3-2 5s.5 3 2 3 2-1 2-3-.5-4-2-5Zm0 8v10"/>',
	'wifi' => '<path d="M5 12.5a10 10 0 0 1 14 0"/><path d="M8 15.5a6 6 0 0 1 8 0"/><circle cx="12" cy="19" r="1"/>',
	'bbq' => '<path d="M5 9h14l-1.5 6a2 2 0 0 1-2 1.5H8.5a2 2 0 0 1-2-1.5Z"/><path d="M9 9V7a3 3 0 0 1 6 0v2M10 19v2M14 19v2"/>',
	'bed' => '<path d="M3 11h18M5 11V7a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v4M4 11v7M20 11v7M4 15h16"/>',
	'home' => '<path d="M4 21V8l8-5 8 5v13M9 21v-6h6v6"/>',
	'pin' => '<circle cx="12" cy="11" r="3"/><path d="M12 2a8 8 0 0 1 8 8c0 5.4-8 12-8 12S4 15.4 4 10a8 8 0 0 1 8-8Z"/>',
);

$TEXT = array(
	'home' => 'Home',
	'houses' => 'Rooms',
	'discover' => 'Discover',
	'show_all_photos' => 'Show all photos',
	'request_availability' => 'Request availability',
	'price_condition' => 'Price & condition',
	'contacts' => 'Contacts',
	'stay_in_touch' => 'Stay in touch',
	'privacy_policy' => 'Privacy Policy',
	'all_rights_reserved' => 'All rights reserved',
	'address' => 'Address',
	'phone' => 'Phone',
	'email' => 'Email',
	'open_maps' => 'Open in Google Maps ->',
	'chat_whatsapp' => 'Chat on WhatsApp',
	'form_name' => 'Name',
	'form_email' => 'Email',
	'form_phone' => 'Phone',
	'form_message' => 'Message',
	'form_name_placeholder' => 'Your name',
	'form_email_placeholder' => 'you@email.com',
	'form_phone_placeholder' => '+39 ...',
	'form_message_placeholder' => 'Tell us about your stay, dates and number of guests...',
	'form_send' => 'Send message',
	'form_result' => 'Thank you - your request has been sent. We will contact you shortly.',
);

$GALLERY = array(
	sbt_t3_asset( 'assets/images/mf-03.jpg' ),
	sbt_t3_asset( 'assets/images/mf-10.jpg' ),
	sbt_t3_asset( 'assets/images/mf-01.jpg' ),
	sbt_t3_asset( 'assets/images/mf-16.jpg' ),
	sbt_t3_asset( 'assets/images/mf-12.jpg' ),
);

$SERVICES = array(
	array( 'pool', 'Pool', 'A pool set among the centuries-old olive trees, with loungers and large pool towels provided.' ),
	array( 'tree', 'Olive Groves', 'Seven hectares of old olive trees and fruit trees to wander, in complete silence.' ),
	array( 'kitchen', 'Two Kitchens', 'Fully equipped with fridge, dishwasher, oven and hob, coffee machine, toaster and tea.' ),
	array( 'wifi', 'Wi-Fi', 'Connectivity across the estate, for whenever you need it.' ),
	array( 'bbq', 'Outdoor Areas', 'Three outdoor areas around the main house, including a pergola for long meals in the shade.' ),
	array( 'bed', 'Linen & Towels', 'Bed linen plus a small, medium and large towel per person, and a professional hairdryer in each bathroom.' ),
	array( 'home', 'Laundry', 'Washing machine, ironing board and clothes hanger at your disposal.' ),
	array( 'pin', 'Strategic Location', 'In the middle of Polignano, Conversano and Castellana Grotte, 15 minutes from Alberobello.' ),
);

$HOUSE_CARDS = array(
	array(
		'tag' => 'Sleep',
		'title' => 'Bedrooms',
		'listing_title' => 'Bedrooms',
		'img' => sbt_t3_asset( 'assets/images/mf-10.jpg' ),
		'gallery' => array( sbt_t3_asset( 'assets/images/mf-10.jpg' ), sbt_t3_asset( 'assets/images/mf-24.jpg' ), sbt_t3_asset( 'assets/images/mf-14.jpg' ) ),
		'url' => 'rooms.php',
		'specs' => array( array( 'Rooms', '4 bedrooms' ), array( 'Style', 'Stone vaults' ), array( 'View', 'Countryside' ) ),
	),
	array(
		'tag' => 'Exclusive use',
		'title' => 'The Whole Masseria',
		'listing_title' => 'Whole Masseria',
		'img' => sbt_t3_asset( 'assets/images/mf-05.jpg' ),
		'gallery' => array( sbt_t3_asset( 'assets/images/mf-05.jpg' ), sbt_t3_asset( 'assets/images/mf-09.jpg' ), sbt_t3_asset( 'assets/images/mf-17.jpg' ) ),
		'url' => 'whole-masseria.php',
		'specs' => array( array( 'Use', 'Exclusive' ), array( 'Outdoors', 'Three areas' ), array( 'Pool', 'Private' ) ),
	),
	array(
		'tag' => 'Outdoors',
		'title' => 'Pool',
		'listing_title' => 'Pool',
		'img' => sbt_t3_asset( 'assets/images/mf-12.jpg' ),
		'gallery' => array( sbt_t3_asset( 'assets/images/mf-12.jpg' ), sbt_t3_asset( 'assets/images/mf-18.jpg' ), sbt_t3_asset( 'assets/images/mf-20.jpg' ) ),
		'url' => 'pool.php',
		'specs' => array( array( 'Setting', 'Olive trees' ), array( 'Comfort', 'Loungers' ), array( 'Towels', 'Included' ) ),
	),
);

$C = array(
	'home' => array(
		'title' => 'Masseria Montefieno - A stunning Masseria in Puglia',
		'hero_over' => 'Masseria Montefieno · Conversano · Puglia',
		'hero_h1' => 'Silence, stillness,<br/>and ancient olives',
		'hero_sub' => 'A masseria in the Puglia countryside, surrounded by seven hectares of centuries-old olive groves and fruit trees.',
		'hero_slides' => array( $IMG['hero_1'], $IMG['hero_2'], $IMG['hero_3'], $IMG['hero_4'] ),
		'scroll_label' => 'Scroll',
		'welcome_over' => 'Welcome',
		'welcome_h2' => 'An idyllic corner<br/>of the Puglia countryside',
		'welcome_p1' => 'Masseria Montefieno sits in an idyllic location in the Puglia countryside, surrounded by seven hectares of picturesque farmland of old olive trees and a selection of fruit trees. Everywhere, silence and stillness.',
		'welcome_p2' => 'Each room has been inspired by the elegance of the simple traditions of Puglia, with magnificent views over the surrounding countryside — made up, for the most part, of centuries-old olive groves.',
		'welcome_url' => 'villa.php',
		'welcome_btn' => 'Discover the Masseria',
		'welcome_gallery' => array( sbt_t3_asset( 'assets/images/mf-05.jpg' ), sbt_t3_asset( 'assets/images/mf-04.jpg' ), sbt_t3_asset( 'assets/images/mf-08.jpg' ), sbt_t3_asset( 'assets/images/mf-02.jpg' ), sbt_t3_asset( 'assets/images/mf-22.jpg' ) ),
		'welcome_stamp' => 'Seven<br/>hectares',
		'gallery_over' => 'A look inside',
		'gallery_h2' => 'Stone, light and tradition',
		'gallery' => array( 'mf-03.jpg', 'mf-10.jpg', 'mf-01.jpg', 'mf-16.jpg', 'mf-12.jpg' ),
		'houses_over' => 'The estate',
		'houses_h2' => 'Two houses among the olives',
		'houses_p' => 'The main structure offers three beautifully restored stone bedrooms with decoration typical of Puglia, two kitchens, three bathrooms, a large living room and three outdoor areas. A second house, 120 metres away, adds one more bedroom with its own bathroom and outdoor space.',
		'rooms' => array(
			array( 'tag' => 'Main house', 'h3' => 'Room 1' ),
			array( 'tag' => 'Main house', 'h3' => 'Room 2' ),
			array( 'tag' => 'Main house', 'h3' => 'Room 3' ),
		),
		'discover_btn' => 'Discover',
		'whole_label' => 'Exclusive use',
		'whole_h3' => 'Book the entire Masseria',
		'whole_p' => 'Reserve all the bedrooms, both houses, the pool and seven hectares of olive groves — the whole of Montefieno, for you and yours alone.',
		'whole_btn' => 'Book entire Masseria',
		'services_over' => 'Comfort & Care',
		'services_h2' => 'The estate at your service',
		'services' => array(
			array( 'h4' => 'Pool', 'p' => 'A pool set among the centuries-old olive trees, with loungers and large pool towels provided.' ),
			array( 'h4' => 'Olive Groves', 'p' => 'Seven hectares of old olive trees and fruit trees to wander, in complete silence.' ),
			array( 'h4' => 'Two Kitchens', 'p' => 'Fully equipped with fridge, dishwasher, oven and hob, coffee machine, toaster and tea.' ),
			array( 'h4' => 'Wi-Fi', 'p' => 'Connectivity across the estate, for whenever you need it.' ),
			array( 'h4' => 'Outdoor Areas', 'p' => 'Three outdoor areas around the main house, including a pergola for long meals in the shade.' ),
			array( 'h4' => 'Linen & Towels', 'p' => 'Bed linen plus a small, medium and large towel per person, and a professional hairdryer in each bathroom.' ),
			array( 'h4' => 'Laundry', 'p' => 'Washing machine, ironing board and clothes hanger at your disposal.' ),
			array( 'h4' => 'Strategic Location', 'p' => 'In the middle of Polignano, Conversano and Castellana Grotte — 15 minutes from Alberobello.' ),
		),
		'band_bg' => sbt_t3_asset( 'assets/images/mf-25.jpg' ),
		'band_over' => 'In the heart of Puglia',
		'band_h2' => 'Between Polignano, Conversano<br/>and Castellana Grotte',
		'band_p' => "Fifteen minutes from the trulli of Alberobello, the beaches of Monopoli and the Itria Valley — explore Apulia's masterpieces of art, architecture and gastronomy.",
		'farm_label' => 'Masseria Montefieno',
		'farm_h3' => 'The Farm',
		'farm_p' => 'The masseria is a working farm: extra-virgin olive oil from the centuries-old grove and Vitus Primitivo wine from our vineyards, made the way they have always been made in this corner of Puglia.',
		'farm_url' => 'farm.php',
		'farm_btn' => 'Discover the farm',
		'farm_gallery' => array( sbt_t3_asset( 'assets/images/mf-27.jpg' ), sbt_t3_asset( 'assets/images/mf-21.jpg' ), sbt_t3_asset( 'assets/images/mf-11.jpg' ), sbt_t3_asset( 'assets/images/mf-13.jpg' ) ),
		'surroundings_label' => 'Masseria Montefieno',
		'surroundings_h3' => 'The Surroundings',
		'surroundings_p' => 'The complex sits at a strategic point for travellers, in the middle of the most representative towns of the area — Polignano a Mare, Conversano and Castellana Grotte — and a 15-minute drive from the trulli of Alberobello, the beaches of Monopoli and the Itria Valley.',
		'surroundings_url' => 'surroundings.php',
		'surroundings_btn' => 'Explore the area',
		'surroundings_gallery' => array( sbt_t3_asset( 'assets/images/mf-25.jpg' ), sbt_t3_asset( 'assets/images/mf-26.jpg' ), sbt_t3_asset( 'assets/images/mf-21.jpg' ) ),
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
		'cta_over' => 'Silence and stillness await',
		'cta_h2' => 'Your stay at<br/>Masseria Montefieno',
		'cta_p' => '',
		'cta_btn' => 'Discover the stay',
		'cta_url' => 'whole-masseria.php',
	),
	'villa' => array(
		'title' => 'The Masseria - Masseria Montefieno',
		'over' => 'Masseria Montefieno',
		'h1' => 'The Masseria',
		'banner' => sbt_t3_asset( 'assets/images/mf-05.jpg' ),
		'intro_over' => 'Restored stone, Apulian soul',
		'intro_h2' => 'Everywhere,<br/>silence and stillness',
		'intro_p1' => 'Masseria Montefieno is situated in an idyllic location in the Puglia countryside, surrounded by seven hectares of picturesque farmland of old olive trees and a selection of fruit trees.',
		'intro_p2' => 'The main structure consists of three bedrooms — all beautifully restored stone with special decoration typical of Puglia — two kitchens, three bathrooms, a large living room and three outdoor areas. The second house, 120 metres from the masseria, is composed of one bedroom, one bathroom and its own outdoor area.',
		'intro_p3' => 'Each room has been inspired by the elegance of the simple traditions of Puglia, and all enjoy magnificent views of the surrounding countryside of centuries-old olive groves.',
		'gallery2' => array( 'mf-00.jpg', 'mf-01.jpg', 'mf-03.jpg', 'mf-07.jpg', 'mf-04.jpg', 'mf-08.jpg' ),
		'am_over' => 'Comfort & independence',
		'am_h2' => 'Every detail, designed for you',
		'am_p' => 'Everything you need for an independent stay in the countryside — provided with the care of a family home.',
		'amenities' => array(
			array( 'h4' => 'Pool', 'p' => 'A pool among the olive trees, with loungers and a large pool towel provided per person.' ),
			array( 'h4' => 'Park & Olive Grove', 'p' => 'Seven hectares of olive and fruit trees, ideal for walks and quiet moments in the open air.' ),
			array( 'h4' => 'Equipped Kitchens', 'p' => 'Fridge, dishwasher, oven and hob, coffee machine, toaster and tea — in both kitchens.' ),
			array( 'h4' => 'Laundry & Ironing', 'p' => 'Washing machine, ironing board and clothes hanger at your disposal.' ),
			array( 'h4' => 'Free Wi-Fi', 'p' => 'Connection in the houses and common areas.' ),
			array( 'h4' => 'Linen & Towels', 'p' => 'Bed linen with three towels per person, and a professional hairdryer in every bathroom.' ),
		),
		'cta_over' => 'Your private retreat awaits',
		'cta_h2' => 'Stay at Masseria Montefieno',
		'cta_btn' => 'Explore the masseria',
		'cta_url' => 'whole-masseria.php',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
	),
	'house' => array(
		'title' => 'Bedrooms - Masseria Montefieno',
		'over' => 'Restored stone',
		'h1' => 'Bedrooms',
		'banner' => sbt_t3_asset( 'assets/images/mf-10.jpg' ),
		'intro_over' => 'Intimate & refined',
		'intro_h2' => 'Sleeping in restored stone',
		'intro_p' => "The main house offers three bedrooms, all beautifully restored stone with special decoration typical of Puglia, served by three bathrooms. Each room is inspired by the elegance of the region's simple traditions, with magnificent views over the centuries-old olive groves.",
		'room_btn' => 'Request availability',
		'rooms' => array(
			array( 'tag' => 'Main house', 'h3' => 'Bedroom One' ),
			array( 'tag' => 'Main house', 'h3' => 'Bedroom Two' ),
			array( 'tag' => 'Main house', 'h3' => 'Bedroom Three' ),
		),
		'second_over' => '120 metres from the masseria',
		'second_h2' => 'The Second House',
		'second_p' => 'A short stroll through the olive trees from the main house, the second house offers one bedroom, one bathroom and its own outdoor area — perfect for guests who want a little extra independence within the estate.',
		'second_specs' => array( array( 'Bedroom', '1' ), array( 'Bathroom', '1' ), array( 'Outdoor area', 'Private' ) ),
		'second_btn' => 'Request availability',
		'inc_over' => "What's included",
		'inc_h2' => 'Comfort in every corner',
		'included' => array(
			array( 'h4' => 'Linen & Towels', 'p' => 'Bed linen plus a small, medium and large towel per person.' ),
			array( 'h4' => 'Pool Towels', 'p' => 'A large pool towel provided per person.' ),
			array( 'h4' => 'Professional Hairdryer', 'p' => 'Available inside each bathroom.' ),
			array( 'h4' => 'Equipped Kitchens', 'p' => 'Fridge, dishwasher, oven and hob, coffee machine, toaster and tea.' ),
			array( 'h4' => 'Laundry & Ironing', 'p' => 'Washing machine, ironing board and clothes hanger.' ),
			array( 'h4' => 'Free Wi-Fi', 'p' => 'Connection in the houses and grounds.' ),
		),
		'cta_over' => 'Ready when you are',
		'cta_h2' => 'Reserve your room',
		'cta_btn' => 'Contact us',
		'cta_url' => 'contacts.php',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-10.jpg' ),
	),
	'whole' => array(
		'title' => 'The Whole Masseria - Masseria Montefieno',
		'over' => 'Exclusive use',
		'h1' => 'The Whole Masseria',
		'banner' => sbt_t3_asset( 'assets/images/mf-05.jpg' ),
		'ov_over' => 'One booking, the entire estate',
		'ov_h2' => 'The masseria, yours alone',
		'ov_p' => 'Book the estate in its entirety: the main house with its three stone bedrooms, two kitchens, three bathrooms, large living room and three outdoor areas — plus the second house, 120 metres away, with its own bedroom, bathroom and outdoor space. The pool and seven hectares of olive groves, reserved exclusively for your party.',
		'specs' => array( array( 'Houses', '2' ), array( 'Bedrooms', '3 + 1' ), array( 'Bathrooms', '3 + 1' ), array( 'Use', 'Entire estate, exclusive' ) ),
		'act_avail' => 'Request availability',
		'act_url' => 'syncbooking:booking',
		'act_price' => 'Price & condition',
		'gallery_over' => 'A look around',
		'gallery_h2' => 'The estate, in detail',
		'inc_over' => "What's included",
		'inc_h2' => 'Everything, exclusively yours',
		'whole_included' => array(
			array( 'h4' => 'Two Houses', 'p' => 'The main house plus the second house, 120 metres apart among the olives.' ),
			array( 'h4' => 'Pool', 'p' => 'Set among the centuries-old olive trees, all yours.' ),
			array( 'h4' => 'Two Kitchens', 'p' => 'Fully equipped, with dining areas indoors and out.' ),
			array( 'h4' => 'Seven Hectares', 'p' => 'Old olive trees and fruit trees, in complete silence.' ),
			array( 'h4' => 'Free Wi-Fi', 'p' => 'Connection across the estate.' ),
			array( 'h4' => 'Linen & Towels', 'p' => 'Bed linen, three towels per person and a large pool towel each.' ),
		),
		'cta_over' => 'Ready when you are',
		'cta_h2' => 'Reserve the whole masseria',
		'cta_btn' => 'Contact us',
		'cta_url' => 'contacts.php',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
	),
	'pool' => array(
		'title' => 'The Pool - Masseria Montefieno',
		'over' => 'Among the olive trees',
		'h1' => 'The Pool',
		'banner' => sbt_t3_asset( 'assets/images/mf-12.jpg' ),
		'intro_over' => 'Water and silver leaves',
		'intro_h2' => 'A pool set<br/>in the olive grove',
		'intro_p1' => 'The pool lies a few steps from the houses, framed on every side by the centuries-old olive trees of the estate. Loungers wait in the shade of the branches, and a large pool towel is provided for each guest.',
		'intro_p2' => 'Mornings of slow swims, afternoons of reading under the trees, evenings when the water reflects the lights of the masseria — the pool is the quiet heart of summer at Montefieno.',
		'action_url' => 'contacts.php',
		'action_btn' => 'Request availability',
		'cta_over' => 'Summer at Montefieno',
		'cta_h2' => 'The olive grove, the water, you',
		'cta_btn' => 'Plan your stay',
		'cta_url' => 'contacts.php',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-12.jpg' ),
	),
	'farm' => array(
		'title' => 'The Farm - Masseria Montefieno',
		'over' => 'Seven hectares of farmland',
		'h1' => 'The Farm',
		'banner' => sbt_t3_asset( 'assets/images/mf-27.jpg' ),
		'intro_over' => 'A working estate',
		'intro_h2' => 'Old olives, fruit trees, vines',
		'intro_p' => 'Masseria Montefieno is surrounded by seven hectares of picturesque farmland — centuries-old olive trees and a selection of fruit trees. The land is still worked as it has always been, and its harvest ends up in the bottle.',
		'oil_label' => 'From our grove',
		'oil_h3' => 'Olive Oil',
		'oil_p' => "Extra-virgin olive oil pressed from the fruit of the estate's centuries-old trees — the same trees that shade your walks and frame the pool. Available from our farm shop.",
		'oil_btn' => 'Visit the shop',
		'wine_label' => 'From our vines',
		'wine_h3' => 'Vitus Primitivo Wine',
		'wine_p' => 'From the vineyards of the estate comes our Vitus Primitivo — a wine with the warmth of the Apulian sun in it, made for long tables and slow evenings.',
		'wine_btn' => 'Visit the shop',
		'shop_url' => 'https://shop.masseriamontefieno.com/',
		'cta_over' => 'Taste the estate',
		'cta_h2' => 'Oil and wine,<br/>born a few steps away',
		'cta_btn' => 'Visit the farm shop',
		'cta_url' => 'contacts.php',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-27.jpg' ),
	),
	'price' => array(
		'title' => 'Price & Condition - Masseria Montefieno',
		'over' => 'Rates & reservations',
		'h1' => 'Price & Condition',
		'banner' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
		'intro_over' => 'Transparent & flexible',
		'intro_h2' => 'Plan your stay with confidence',
		'intro_p' => 'Check live availability and the best rates, then confirm your reservation in a few secure steps — instant booking, no waiting for a reply.',
		'bc_over' => 'Real-time availability',
		'bc_h3' => 'Check dates & book online',
		'bc_p' => 'Select your dates, see live prices and complete your reservation through our secure booking system.',
		'bc_url' => 'syncbooking:booking',
		'bc_btn' => 'Book your stay',
		'bc_note' => 'Best rate guaranteed when you book direct.',
		'cond_over' => 'Good to know',
		'cond_h2' => 'Conditions',
		'conditions' => array(
			array( 'dt' => 'Check-in', 'dd' => 'From 3:00 PM. Late arrivals can be arranged on request.' ),
			array( 'dt' => 'Check-out', 'dd' => 'By 10:30 AM on the day of departure.' ),
			array( 'dt' => 'Minimum stay', 'dd' => '2 nights; longer in high season and during special periods.' ),
			array( 'dt' => 'Included', 'dd' => 'Final cleaning, bed linen and towels, pool towels, Wi-Fi, pool and grounds access.' ),
			array( 'dt' => 'City tax', 'dd' => 'Applied per person/night as required by the Municipality of Conversano.' ),
			array( 'dt' => 'Pets', 'dd' => 'Welcome on request — please let us know in advance.' ),
		),
		'cta_over' => 'Tailored to your dates',
		'cta_h2' => 'Request your personalised quote',
		'cta_btn' => 'Contact us',
		'cta_url' => 'contacts.php',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
	),
	'surroundings' => array(
		'title' => 'Surroundings - Masseria Montefieno',
		'over' => 'Conversano & beyond',
		'h1' => 'Surroundings',
		'banner' => sbt_t3_asset( 'assets/images/mf-25.jpg' ),
		'intro_over' => 'In the heart of Puglia',
		'intro_h2' => 'A strategic point for travellers',
		'intro_p' => "The masseria sits in the middle of the most representative towns of the area — Polignano a Mare, Conversano and Castellana Grotte — and a 15-minute drive from the beautiful trulli of Alberobello, the beaches of Monopoli and the Itria Valley. Explore Apulia's masterpieces of art, architecture and gastronomy, and unparalleled fine living.",
		'cards' => array(
			array( 'over' => '10 min', 'h3' => 'Conversano', 'url' => 'post:conversano' ),
			array( 'over' => '15 min', 'h3' => 'Polignano a Mare', 'url' => 'post:polignano-a-mare' ),
			array( 'over' => '10 min', 'h3' => 'Castellana Grotte', 'url' => 'post:castellana-grotte' ),
			array( 'over' => '15 min', 'h3' => 'Alberobello & Itria Valley', 'url' => 'post:alberobello-itria-valley' ),
		),
		'band_over' => 'Let us guide you',
		'band_h2' => 'Discover Puglia from Montefieno',
		'band_btn' => 'Plan your stay',
		'band_url' => 'contacts.php',
		'cta_over' => 'Explore Puglia',
		'cta_h2' => 'Start from Montefieno',
		'cta_btn' => 'Contact us',
		'cta_url' => 'contacts.php',
		'cta_bg' => sbt_t3_asset( 'assets/images/mf-25.jpg' ),
	),
	'contacts' => array(
		'title' => 'Contacts - Masseria Montefieno',
		'over' => 'We are here for you',
		'h1' => 'Contacts',
		'banner' => sbt_t3_asset( 'assets/images/mf-22.jpg' ),
		'intro_over' => 'Get in touch',
		'intro_h2' => 'Plan your stay with us',
		'intro_p' => 'For availability, tailored quotes or any request, we will be delighted to help. Reach us by phone, email or WhatsApp — or send a message using the form and we will reply as soon as possible.',
		'addr_over' => 'Address',
		'addr_lines' => 'Masseria Montefieno<br/>Conversano (Bari)<br/>Puglia, Italy',
		'maps_label' => 'Open in Google Maps →',
		'phone_over' => 'Phone',
		'wa_label' => 'Chat on WhatsApp',
		'email_over' => 'Email',
	),
);

if ( function_exists( 'sbt_bootstrap_content' ) ) {
	sbt_bootstrap_content( $IMG, $SITE, $NAV, $C, $HOUSE_CARDS, $SERVICES, $TEXT, $GALLERY );
}
